max_steps: 300
maze_grid_size: 10
brain:
  name: mlp
  config:
    baseline: 0.0
    baseline_alpha: 0.05
    entropy_beta: 0.01
    gamma: 0.99
    hidden_dim: 64
    learning_rate: 0.001
    lr_scheduler_step_size: 100
    lr_scheduler_gamma: 0.9
    num_hidden_layers: 2
shots: 1000
body_length: 2
qubits: 2
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.001
    decay_rate: 0.0001
    decay_type: inverse_time
reward:
  reward_goal: 2.0
  reward_distance_scale: 0.5
  penalty_step: 0.005
  penalty_anti_dithering: 0.02
  penalty_stuck_position: 0.1
  stuck_position_threshold: 3
gradient:
  method: clip
