max_steps: 300
maze_grid_size: 10
brain:
  name: modular
  config:
    modules:
      chemotaxis: [0, 1]
    num_layers: 2
    gradient_norm_threshold: 1e-6
    min_gradient_magnitude: 1e-8
    l2_reg: 0.0005
    noise_std: 0.003
    param_clip: true
    param_modulo: true
shots: 1500
body_length: 2
qubits: 2
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.12
    decay_type: cosine
    min_lr: 0.0002
    max_steps: 300
reward:
  reward_goal: 1.5
  reward_distance_scale: 0.25
  penalty_step: 0.01
  penalty_anti_dithering: 0.05
  penalty_stuck_position: 0.05
  stuck_position_threshold: 2
superposition_mode:
  max_superpositions: 32
  max_columns: 8
  render_sleep_seconds: 0.5
  top_n_actions: 2
  top_n_randomize: true
