max_steps: 300
maze_grid_size: 10
brain:
  name: modular
  config:
    modules:
      chemotaxis: [0, 1]
    num_layers: 2
    min_gradient_magnitude: 1e-8
    l2_reg: 0.0005
    noise_std: 0.003
    param_clip: true
    param_modulo: true
shots: 1500
body_length: 2
qubits: 2
parameter_initializer:
  type: manual
  manual_parameter_values:
    θ_rx1_0: -2.108816178453594
    θ_rx1_1: -3.0332470081378125
    θ_rx2_0: -1.0286876946120325
    θ_rx2_1: -2.722634632987353
    θ_ry1_0: 2.6505971956958057
    θ_ry1_1: -2.098690045703495
    θ_ry2_0: 2.9949810403489963
    θ_ry2_1: 1.0212932978368165
    θ_rz1_0: 0.274998199369362
    θ_rz1_1: 2.991841394298831
    θ_rz2_0: 0.11945105853440685
    θ_rz2_1: -0.5333167212405057
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.1
    decay_type: inverse_time
    decay_rate: 0.5
    min_lr: 0
reward:
  reward_goal: 2.0
  reward_distance_scale: 0.5
  penalty_step: 0.005
  penalty_anti_dithering: 0.02
  penalty_stuck_position: 0.1
  stuck_position_threshold: 10
manyworlds_mode:
  max_superpositions: 32
  max_columns: 8
  render_sleep_seconds: 0.5
  top_n_actions: 2
  top_n_randomize: true
