max_steps: 300
maze_grid_size: 10
brain:
  name: modular
  config:
    modules:
      chemotaxis: [0, 1]
    num_layers: 2
    min_gradient_magnitude: 1e-8
    l2_reg: 0.01
    noise_std: 0.01
    param_clip: true
    param_modulo: true
shots: 1500
body_length: 2
qubits: 2
parameter_initializer:
  type: random_pi
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 1.0
    decay_type: inverse_time
    decay_rate: 0.1
    min_lr: 0
reward:
  reward_goal: 2.0
  reward_distance_scale: 0.5
  penalty_step: 0.005
  penalty_anti_dithering: 0.02
  penalty_stuck_position: 0.1
  stuck_position_threshold: 10
manyworlds_mode:
  max_superpositions: 32
  max_columns: 8
  render_sleep_seconds: 0.5
  top_n_actions: 2
  top_n_randomize: true
