max_steps: 300
maze_grid_size: 10
brain:
  name: qmlp
  config:
    hidden_dim: 64
    learning_rate: 0.001
    epsilon: 0.1
    epsilon_decay: 0.995
    epsilon_min: 0.01
    gamma: 0.95
    target_update_freq: 100
    num_hidden_layers: 2
shots: 1000
body_length: 2
qubits: 2
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.001
    decay_rate: 0.0001
    decay_type: inverse_time
reward:
  reward_goal: 2.0
  reward_distance_scale: 0.5
  penalty_step: 0.005
  penalty_anti_dithering: 0.02
  penalty_stuck_position: 0.1
  stuck_position_threshold: 3
gradient:
  method: clip
