"""302-neuron *C. elegans* hermaphrodite classification table.

The ``NEURON_CLASSIFICATION`` dict below is the canonical project reference
for *C. elegans* neuron identities. It is derived from OpenWorm cect's
MIT-licensed ``Cells.py`` constants (``SENSORY_NEURONS_COOK``,
``INTERNEURONS_COOK``, ``MOTORNEURONS_COOK``, ``PHARYNGEAL_NEURONS``), which
cect itself attributes to "supplementary info of Cook et al 2019" + WormAtlas.

Attribution chain (top to bottom = derived from):

1. This module (``quantumnematode.connectome.neurons``)
2. cect ``Cells.py`` v0.3.1, MIT-licensed
   <https://github.com/openworm/ConnectomeToolbox>
3. Cook et al. 2019 *Nature* paper + tables + WormAtlas (cect's own
   upstream attribution).

There is **no runtime dependency on cect** — the dict below is a static
Python literal generated once at curation time. See
``data/connectome/PROVENANCE.md`` for the cect version pinned at curation.

Cell-class assignment rules:

- ``"sensory"`` / ``"interneuron"`` / ``"motor"``: from cect's main
  ``SENSORY_NEURONS_COOK`` / ``INTERNEURONS_COOK`` / ``MOTORNEURONS_COOK``
  lists. These three are disjoint in cect's curation.
- ``"pharyngeal"``: from cect's ``PHARYNGEAL_NEURONS`` zone list. This
  overrides sensory/inter/motor for the 20 pharyngeal cells (the data
  model's ``CellClass`` treats "pharyngeal" as a class, not a zone).
- Canal cells (CANL, CANR): cect classifies these as "Other"
  (``get_SIM_class()``); the project data model has no "other" class, so
  they are classified as ``"interneuron"`` (the closest fit per WormAtlas).

Neurotransmitter coverage is intentionally sparse: ``None`` for every
neuron in this initial table. A follow-up curation can attach NTs where
well-documented (Glutamate for ASE / AWC, GABA for VD/DD, Acetylcholine
for VA/VB/DA/DB, Serotonin for NSM/HSN, Dopamine for ADE/PDE/CEP, etc.) —
the project's ``docs/nematode_biology.md`` § Neurotransmitter Systems
lists the well-known cases.

The ``CANONICAL_NAME_ALIASES`` dict normalises cross-dataset naming
quirks (e.g. ``RIA-L`` → ``RIAL``) so the loader can compare Cook 2019
adjacency-matrix headers against Witvliet 2021 column names without
spurious "neuron not found" failures.
"""

from quantumnematode.connectome.model import CellClass

NEURON_CLASSIFICATION: dict[str, tuple[CellClass, str | None]] = {
    "ADAL": ("interneuron", None),
    "ADAR": ("interneuron", None),
    "ADEL": ("sensory", None),
    "ADER": ("sensory", None),
    "ADFL": ("sensory", None),
    "ADFR": ("sensory", None),
    "ADLL": ("sensory", None),
    "ADLR": ("sensory", None),
    "AFDL": ("sensory", None),
    "AFDR": ("sensory", None),
    "AIAL": ("interneuron", None),
    "AIAR": ("interneuron", None),
    "AIBL": ("interneuron", None),
    "AIBR": ("interneuron", None),
    "AIML": ("interneuron", None),
    "AIMR": ("interneuron", None),
    "AINL": ("interneuron", None),
    "AINR": ("interneuron", None),
    "AIYL": ("interneuron", None),
    "AIYR": ("interneuron", None),
    "AIZL": ("interneuron", None),
    "AIZR": ("interneuron", None),
    "ALA": ("interneuron", None),
    "ALML": ("sensory", None),
    "ALMR": ("sensory", None),
    "ALNL": ("sensory", None),
    "ALNR": ("sensory", None),
    "AQR": ("sensory", None),
    "AS1": ("motor", None),
    "AS10": ("motor", None),
    "AS11": ("motor", None),
    "AS2": ("motor", None),
    "AS3": ("motor", None),
    "AS4": ("motor", None),
    "AS5": ("motor", None),
    "AS6": ("motor", None),
    "AS7": ("motor", None),
    "AS8": ("motor", None),
    "AS9": ("motor", None),
    "ASEL": ("sensory", None),
    "ASER": ("sensory", None),
    "ASGL": ("sensory", None),
    "ASGR": ("sensory", None),
    "ASHL": ("sensory", None),
    "ASHR": ("sensory", None),
    "ASIL": ("sensory", None),
    "ASIR": ("sensory", None),
    "ASJL": ("sensory", None),
    "ASJR": ("sensory", None),
    "ASKL": ("sensory", None),
    "ASKR": ("sensory", None),
    "AUAL": ("interneuron", None),
    "AUAR": ("interneuron", None),
    "AVAL": ("interneuron", None),
    "AVAR": ("interneuron", None),
    "AVBL": ("interneuron", None),
    "AVBR": ("interneuron", None),
    "AVDL": ("interneuron", None),
    "AVDR": ("interneuron", None),
    "AVEL": ("interneuron", None),
    "AVER": ("interneuron", None),
    "AVFL": ("interneuron", None),
    "AVFR": ("interneuron", None),
    "AVG": ("interneuron", None),
    "AVHL": ("interneuron", None),
    "AVHR": ("interneuron", None),
    "AVJL": ("interneuron", None),
    "AVJR": ("interneuron", None),
    "AVKL": ("interneuron", None),
    "AVKR": ("interneuron", None),
    "AVL": ("interneuron", None),
    "AVM": ("sensory", None),
    "AWAL": ("sensory", None),
    "AWAR": ("sensory", None),
    "AWBL": ("sensory", None),
    "AWBR": ("sensory", None),
    "AWCL": ("sensory", None),
    "AWCR": ("sensory", None),
    "BAGL": ("sensory", None),
    "BAGR": ("sensory", None),
    "BDUL": ("interneuron", None),
    "BDUR": ("interneuron", None),
    # CANL/CANR — canal cells; cect classifies as "Other"; project data
    # model uses "interneuron" as the closest fit.
    "CANL": ("interneuron", None),
    "CANR": ("interneuron", None),
    "CEPDL": ("sensory", None),
    "CEPDR": ("sensory", None),
    "CEPVL": ("sensory", None),
    "CEPVR": ("sensory", None),
    "DA1": ("motor", None),
    "DA2": ("motor", None),
    "DA3": ("motor", None),
    "DA4": ("motor", None),
    "DA5": ("motor", None),
    "DA6": ("motor", None),
    "DA7": ("motor", None),
    "DA8": ("motor", None),
    "DA9": ("motor", None),
    "DB1": ("motor", None),
    "DB2": ("motor", None),
    "DB3": ("motor", None),
    "DB4": ("motor", None),
    "DB5": ("motor", None),
    "DB6": ("motor", None),
    "DB7": ("motor", None),
    "DD1": ("motor", None),
    "DD2": ("motor", None),
    "DD3": ("motor", None),
    "DD4": ("motor", None),
    "DD5": ("motor", None),
    "DD6": ("motor", None),
    "DVA": ("sensory", None),
    "DVB": ("interneuron", None),
    "DVC": ("interneuron", None),
    "FLPL": ("sensory", None),
    "FLPR": ("sensory", None),
    "HSNL": ("motor", None),
    "HSNR": ("motor", None),
    "I1L": ("pharyngeal", None),
    "I1R": ("pharyngeal", None),
    "I2L": ("pharyngeal", None),
    "I2R": ("pharyngeal", None),
    "I3": ("pharyngeal", None),
    "I4": ("pharyngeal", None),
    "I5": ("pharyngeal", None),
    "I6": ("pharyngeal", None),
    "IL1DL": ("sensory", None),
    "IL1DR": ("sensory", None),
    "IL1L": ("sensory", None),
    "IL1R": ("sensory", None),
    "IL1VL": ("sensory", None),
    "IL1VR": ("sensory", None),
    "IL2DL": ("sensory", None),
    "IL2DR": ("sensory", None),
    "IL2L": ("sensory", None),
    "IL2R": ("sensory", None),
    "IL2VL": ("sensory", None),
    "IL2VR": ("sensory", None),
    "LUAL": ("interneuron", None),
    "LUAR": ("interneuron", None),
    "M1": ("pharyngeal", None),
    "M2L": ("pharyngeal", None),
    "M2R": ("pharyngeal", None),
    "M3L": ("pharyngeal", None),
    "M3R": ("pharyngeal", None),
    "M4": ("pharyngeal", None),
    "M5": ("pharyngeal", None),
    "MCL": ("pharyngeal", None),
    "MCR": ("pharyngeal", None),
    "MI": ("pharyngeal", None),
    "NSML": ("pharyngeal", None),
    "NSMR": ("pharyngeal", None),
    "OLLL": ("sensory", None),
    "OLLR": ("sensory", None),
    "OLQDL": ("sensory", None),
    "OLQDR": ("sensory", None),
    "OLQVL": ("sensory", None),
    "OLQVR": ("sensory", None),
    "PDA": ("motor", None),
    "PDB": ("motor", None),
    "PDEL": ("sensory", None),
    "PDER": ("sensory", None),
    "PHAL": ("sensory", None),
    "PHAR": ("sensory", None),
    "PHBL": ("sensory", None),
    "PHBR": ("sensory", None),
    "PHCL": ("sensory", None),
    "PHCR": ("sensory", None),
    "PLML": ("sensory", None),
    "PLMR": ("sensory", None),
    "PLNL": ("sensory", None),
    "PLNR": ("sensory", None),
    "PQR": ("sensory", None),
    "PVCL": ("interneuron", None),
    "PVCR": ("interneuron", None),
    "PVDL": ("sensory", None),
    "PVDR": ("sensory", None),
    "PVM": ("sensory", None),
    "PVNL": ("interneuron", None),
    "PVNR": ("interneuron", None),
    "PVPL": ("interneuron", None),
    "PVPR": ("interneuron", None),
    "PVQL": ("interneuron", None),
    "PVQR": ("interneuron", None),
    "PVR": ("interneuron", None),
    "PVT": ("interneuron", None),
    "PVWL": ("interneuron", None),
    "PVWR": ("interneuron", None),
    "RIAL": ("interneuron", None),
    "RIAR": ("interneuron", None),
    "RIBL": ("interneuron", None),
    "RIBR": ("interneuron", None),
    "RICL": ("interneuron", None),
    "RICR": ("interneuron", None),
    "RID": ("interneuron", None),
    "RIFL": ("interneuron", None),
    "RIFR": ("interneuron", None),
    "RIGL": ("interneuron", None),
    "RIGR": ("interneuron", None),
    "RIH": ("interneuron", None),
    "RIML": ("interneuron", None),
    "RIMR": ("interneuron", None),
    "RIPL": ("interneuron", None),
    "RIPR": ("interneuron", None),
    "RIR": ("interneuron", None),
    "RIS": ("interneuron", None),
    "RIVL": ("motor", None),
    "RIVR": ("motor", None),
    "RMDDL": ("motor", None),
    "RMDDR": ("motor", None),
    "RMDL": ("motor", None),
    "RMDR": ("motor", None),
    "RMDVL": ("motor", None),
    "RMDVR": ("motor", None),
    "RMED": ("motor", None),
    "RMEL": ("motor", None),
    "RMER": ("motor", None),
    "RMEV": ("motor", None),
    "RMFL": ("interneuron", None),
    "RMFR": ("interneuron", None),
    "RMGL": ("interneuron", None),
    "RMGR": ("interneuron", None),
    "RMHL": ("motor", None),
    "RMHR": ("motor", None),
    "SAADL": ("interneuron", None),
    "SAADR": ("interneuron", None),
    "SAAVL": ("interneuron", None),
    "SAAVR": ("interneuron", None),
    "SABD": ("motor", None),
    "SABVL": ("motor", None),
    "SABVR": ("motor", None),
    "SDQL": ("sensory", None),
    "SDQR": ("sensory", None),
    "SIADL": ("motor", None),
    "SIADR": ("motor", None),
    "SIAVL": ("motor", None),
    "SIAVR": ("motor", None),
    "SIBDL": ("motor", None),
    "SIBDR": ("motor", None),
    "SIBVL": ("motor", None),
    "SIBVR": ("motor", None),
    "SMBDL": ("motor", None),
    "SMBDR": ("motor", None),
    "SMBVL": ("motor", None),
    "SMBVR": ("motor", None),
    "SMDDL": ("motor", None),
    "SMDDR": ("motor", None),
    "SMDVL": ("motor", None),
    "SMDVR": ("motor", None),
    "URADL": ("motor", None),
    "URADR": ("motor", None),
    "URAVL": ("motor", None),
    "URAVR": ("motor", None),
    "URBL": ("interneuron", None),
    "URBR": ("interneuron", None),
    "URXL": ("sensory", None),
    "URXR": ("sensory", None),
    "URYDL": ("sensory", None),
    "URYDR": ("sensory", None),
    "URYVL": ("sensory", None),
    "URYVR": ("sensory", None),
    "VA1": ("motor", None),
    "VA10": ("motor", None),
    "VA11": ("motor", None),
    "VA12": ("motor", None),
    "VA2": ("motor", None),
    "VA3": ("motor", None),
    "VA4": ("motor", None),
    "VA5": ("motor", None),
    "VA6": ("motor", None),
    "VA7": ("motor", None),
    "VA8": ("motor", None),
    "VA9": ("motor", None),
    "VB1": ("motor", None),
    "VB10": ("motor", None),
    "VB11": ("motor", None),
    "VB2": ("motor", None),
    "VB3": ("motor", None),
    "VB4": ("motor", None),
    "VB5": ("motor", None),
    "VB6": ("motor", None),
    "VB7": ("motor", None),
    "VB8": ("motor", None),
    "VB9": ("motor", None),
    "VC1": ("motor", None),
    "VC2": ("motor", None),
    "VC3": ("motor", None),
    "VC4": ("motor", None),
    "VC5": ("motor", None),
    "VC6": ("motor", None),
    "VD1": ("motor", None),
    "VD10": ("motor", None),
    "VD11": ("motor", None),
    "VD12": ("motor", None),
    "VD13": ("motor", None),
    "VD2": ("motor", None),
    "VD3": ("motor", None),
    "VD4": ("motor", None),
    "VD5": ("motor", None),
    "VD6": ("motor", None),
    "VD7": ("motor", None),
    "VD8": ("motor", None),
    "VD9": ("motor", None),
}

CANONICAL_NAME_ALIASES: dict[str, str] = {
    # Cross-dataset name normalisation. Map non-canonical variants to the
    # canonical form used by NEURON_CLASSIFICATION above.
    # Witvliet 2021 and other datasets sometimes use hyphenated suffixes
    # (e.g. "RIA-L") where Cook 2019 uses unsuffixed (e.g. "RIAL"). Add
    # entries here as the loader encounters them.
}


EXPECTED_NEURON_COUNT = 302
"""Expected size of NEURON_CLASSIFICATION. Asserted at import time."""

if len(NEURON_CLASSIFICATION) != EXPECTED_NEURON_COUNT:
    msg = (
        f"NEURON_CLASSIFICATION has {len(NEURON_CLASSIFICATION)} entries; "
        f"expected exactly {EXPECTED_NEURON_COUNT} for the Cook 2019 "
        "hermaphrodite connectome."
    )
    raise AssertionError(msg)
