#!/usr/bin/env python
"""Emit B.2a's configs: the dynamical wild type at each pilot time constant, and the thermal MLP.

Each dynamical config is its settling parent -- the wild type at block V's committed point on one
cell, learning or frozen -- with ``dynamics: leaky`` and one ``membrane_tau_steps`` added, and
nothing else changed. The MLP-PPO config for thermal target 35 is that cell's connectome config
with its brain replaced by the existing thermal MLP-PPO brain, so the cell (environment, episode
length, reward, satiety) is the connectome arms' exactly. A test re-reads every file through the
real loader to check both. A config that already exists is left alone, never overwritten.

Usage::

    uv run python scripts/campaigns/generate_across_step_configs.py --dry-run
    uv run python scripts/campaigns/generate_across_step_configs.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCENARIOS = PROJECT_ROOT / "configs" / "scenarios"
_HARD = "connectomeppo_small_continuous2d_fick_adaptive_klinotaxis_hard350"
_THERMAL = "connectomeppo_small_continuous2d_thermal_klinotaxis"
# Cell -> (scenario directory, settling learning parent, settling frozen parent).
CELLS: dict[str, tuple[str, str, str]] = {
    "hard350": ("foraging", _HARD, f"{_HARD}_frozen"),
    "thermal": ("thermal_foraging", f"{_THERMAL}_t35", f"{_THERMAL}_frozen_t35"),
}
# The pilot's candidate time constants, in environment steps.
TAUS: tuple[float, ...] = (0.2, 1.0, 5.0)
# Input gains a config set is written at: 1 (the first pilot, which found the substrate attenuating
# the sensory signal) and the gain the calibration chose from untrained brains.
INPUT_GAINS: tuple[float, ...] = (1.0, 512.0)
MLP_PARENT = "mlpppo_small_continuous2d_thermal_klinotaxis"
MLP_STEM = f"{MLP_PARENT}_t35"


def tau_tag(tau: float) -> str:
    """Return the stem suffix for a time constant: ``0.2`` -> ``tau0p2``, ``1.0`` -> ``tau1``."""
    return "tau" + f"{tau:g}".replace(".", "p")


def leaky_stem(parent: str, tau: float, input_gain: float = 1.0) -> str:
    """Return the stem of ``parent`` under leaky dynamics at ``tau`` and ``input_gain``."""
    gain = "" if input_gain == 1.0 else f"ig{input_gain:g}_"
    return f"{parent}_leaky_{gain}{tau_tag(tau)}"


def _load(scenario: str, stem: str) -> dict:
    return yaml.safe_load((SCENARIOS / scenario / f"{stem}.yml").read_text())


def derive_leaky(
    scenario: str,
    parent: str,
    tau: float,
    input_gain: float = 1.0,
) -> tuple[Path, str]:
    """Build one dynamical config: its settling parent with the dynamics keys added."""
    data = _load(scenario, parent)
    brain = data["brain"]["config"]
    if brain.get("dynamics", "settling") != "settling":
        msg = f"{parent}.yml is not a settling config"
        raise ValueError(msg)
    brain["dynamics"] = "leaky"
    brain["membrane_tau_steps"] = tau
    if input_gain != 1.0:
        brain["input_gain"] = input_gain
    gain_line = "" if input_gain == 1.0 else f"#   brain.config.input_gain: {input_gain:g}\n"
    header = (
        f"# Leaky-dynamics wild type, membrane_tau_steps {tau:g}, input_gain {input_gain:g}.\n"
        f"#\n"
        f"# Delta from {parent}.yml, and nothing else changes:\n"
        f"#   brain.config.dynamics: leaky\n"
        f"#   brain.config.membrane_tau_steps: {tau:g}\n"
        f"{gain_line}"
        f"#\n"
        f"# Each neuron carries a membrane potential across steps; gap junctions couple potentials\n"
        f"# ohmically; the sensors enter as a current held through the step.\n"
        f"#\n"
        f"# Generated by scripts/campaigns/generate_across_step_configs.py. The body below is the\n"
        f"# parent's keys, re-emitted -- read that file for the cell's provenance. The delta above is\n"
        f"# re-checked through the real config loader by test_across_step_control.py.\n"
        f"#\n"
    )
    path = SCENARIOS / scenario / f"{leaky_stem(parent, tau, input_gain)}.yml"
    return path, header + yaml.safe_dump(data, sort_keys=False)


def derive_mlp() -> tuple[Path, str]:
    """Build the thermal target-35 MLP-PPO config: the connectome cell with the MLP brain."""
    scenario, parent, _frozen = CELLS["thermal"]
    data = _load(scenario, parent)
    data["brain"] = _load(scenario, MLP_PARENT)["brain"]
    header = (
        "# MLP-PPO on block V's thermal cell at target 35: the positive control that the cell is\n"
        "# solvable by the strongest available method.\n"
        "#\n"
        f"# Every key except brain is {parent}.yml's; brain is {MLP_PARENT}.yml's.\n"
        "#\n"
        "# Generated by scripts/campaigns/generate_across_step_configs.py; re-checked through the\n"
        "# real config loader by test_across_step_control.py.\n"
        "#\n"
    )
    return SCENARIOS / scenario / f"{MLP_STEM}.yml", header + yaml.safe_dump(data, sort_keys=False)


def planned() -> list[tuple[Path, str]]:
    """Every config this script writes, in a fixed order."""
    out = [
        derive_leaky(scenario, parent, tau, gain)
        for gain in INPUT_GAINS
        for scenario, learn, frozen in CELLS.values()
        for parent in (learn, frozen)
        for tau in TAUS
    ]
    out.append(derive_mlp())
    return out


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--dry-run", action="store_true", help="list what would be written")
    args = ap.parse_args(argv)
    written, kept = 0, 0
    for path, text in planned():
        if path.exists():
            kept += 1
            continue
        written += 1
        if args.dry_run:
            print(f"would write {path.relative_to(PROJECT_ROOT)}")
        else:
            path.write_text(text)
    print(f"{'would write' if args.dry_run else 'wrote'} {written} configs; kept {kept}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
