#!/usr/bin/env python
"""Emit C.1e's configs: the connectome's wirings through the kinematic body, and the MLP beside.

Every connectome config is C.0's Emmons 2024 reversal pair with the body switched on: the kinematic
body model, the 25-number body-drive action, signed speed removed (the body's direction channel
reverses it), the 500-step episode C.1d's fallback chose, and an ``entropy_coef`` of 0.004, the
point-worm configs' per-dimension entropy pressure on the body's 25 action numbers. Beyond that each
arm sets its wiring and its learner:

* ``ppo``: PPO, writing the chemical weights;
* ``fw``: PPO with ``freeze_wiring``, reading the wiring without writing it;
* ``frozen``: the frozen floor, one per wiring, shared by both learners.

The MLP arm is C.1d's 500-step control at the same entropy. Each config is re-checked through the
real loader by a test. A config that already exists is left alone, never overwritten.

* ``--stage pilot``: the wild type and the chemical-only null, every learner.
* ``--stage panel``: the pilot's PPO and frozen arms (the same configs, on fresh seeds) and the MLP.
* ``--stage boundary``: the boundary-preserving null, PPO and frozen, written only if the panel's
  reading opens its stage.

Usage::

    uv run python scripts/campaigns/generate_body_wiring_configs.py --stage pilot
    uv run python scripts/campaigns/generate_body_wiring_configs.py --stage panel
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FORAGING = PROJECT_ROOT / "configs" / "scenarios" / "foraging"
_CONNECTOME = "connectomeppo_small_continuous2d_fick_adaptive_klinotaxis_hard350"
PARENTS = {
    "learn": f"{_CONNECTOME}_emmons_reversal",
    "frozen": f"{_CONNECTOME}_frozen_emmons_reversal",
}
MLP_PARENT = "mlpppo_small_continuous2d_fick_adaptive_klinotaxis_hard350_ppo_w64_body_steps500"
MAX_STEPS = 500
ENTROPY_COEF = 0.004

# Wiring tag -> the brain's wiring value.
WIRINGS: dict[str, str] = {
    "wt": "wild_type",
    "chemnull": "rewired_chemical_only",
    "boundary": "rewired_boundary_held",
    "current": "rewired_degree_preserving",
}
LEARNERS: tuple[str, ...] = ("ppo", "fw", "frozen")
PILOT_WIRINGS: tuple[str, ...] = ("wt", "chemnull")


def stem(wiring: str, learner: str) -> str:
    """Return one connectome arm's config stem."""
    return f"{_CONNECTOME}_body500_{wiring}_{learner}"


MLP_STEM = "mlpppo_small_continuous2d_fick_adaptive_klinotaxis_hard350_ppo_w64_body500"


def derive(wiring: str, learner: str) -> tuple[Path, str]:
    """Build one connectome arm from its C.0 parent with the body on and its wiring and learner."""
    parent = PARENTS["frozen" if learner == "frozen" else "learn"]
    data: dict[str, Any] = yaml.safe_load((FORAGING / f"{parent}.yml").read_text())
    data["max_steps"] = MAX_STEPS
    data["environment"]["continuous"]["body_model"] = "kinematic"
    brain = data["brain"]["config"]
    brain["action_space"] = "body_drive"
    del brain["signed_speed"]
    brain["entropy_coef"] = ENTROPY_COEF
    brain["wiring"] = WIRINGS[wiring]
    lines = [
        f"max_steps: {MAX_STEPS}",
        "environment.continuous.body_model: kinematic",
        "brain.config.action_space: body_drive",
        "brain.config.signed_speed: removed",
        f"brain.config.entropy_coef: {ENTROPY_COEF}",
        f"brain.config.wiring: {WIRINGS[wiring]}",
    ]
    if learner == "fw":
        brain["freeze_wiring"] = True
        lines.append("brain.config.freeze_wiring: true")
    return _write(stem(wiring, learner), parent, data, lines)


def derive_mlp() -> tuple[Path, str]:
    """Build the MLP arm: C.1d's 500-step control at the body arms' entropy."""
    data: dict[str, Any] = yaml.safe_load((FORAGING / f"{MLP_PARENT}.yml").read_text())
    data["brain"]["config"]["entropy_coef"] = ENTROPY_COEF
    return _write(MLP_STEM, MLP_PARENT, data, [f"brain.config.entropy_coef: {ENTROPY_COEF}"])


def _write(child: str, parent: str, data: dict[str, Any], lines: list[str]) -> tuple[Path, str]:
    header = (
        f"# C.1e arm: {child}.\n#\n# Delta from {parent}.yml, and nothing else changes:\n"
        + "".join(f"#   {line}\n" for line in lines)
        + "#\n# Generated by scripts/campaigns/generate_body_wiring_configs.py; re-checked\n"
        "# through the real config loader by test_body_wiring.py.\n#\n"
    )
    return FORAGING / f"{child}.yml", header + yaml.safe_dump(data, sort_keys=False)


def stage_configs(stage: str) -> list[tuple[Path, str]]:
    """Return every ``(path, text)`` one stage writes."""
    if stage == "pilot":
        return [derive(w, learner) for w in PILOT_WIRINGS for learner in LEARNERS]
    if stage == "panel":
        return [derive(w, learner) for w in PILOT_WIRINGS for learner in ("ppo", "frozen")] + [
            derive_mlp(),
        ]
    if stage == "boundary":
        return [derive("boundary", learner) for learner in ("ppo", "frozen")]
    msg = f"unknown stage {stage!r}"
    raise ValueError(msg)


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config of one stage, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--stage", choices=("pilot", "panel", "boundary"), required=True)
    args = ap.parse_args(argv)
    configs = stage_configs(args.stage)
    written = 0
    for path, text in configs:
        if not path.exists():
            path.write_text(text)
            written += 1
    print(f"wrote {written} configs; kept {len(configs) - written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
