#!/usr/bin/env python
"""Emit C.0's validation configs: MLP-PPO and the connectome on hard350 with reversal on.

Four configs, each a committed hard350 parent with only the listed keys changed, re-checked through
the real loader by a test:

* MLP-PPO, learning and frozen: the width-64 hard350 MLP-PPO config with reversal on (and
  ``freeze_updates`` for the floor).
* The connectome's settling wild type, learning and frozen: block V's hard350 arms with reversal on
  and the Emmons 2024 source, 8b's substrate.

A config that already exists is left alone, never overwritten.

Usage::

    uv run python scripts/campaigns/generate_body_prerequisite_configs.py
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FORAGING = PROJECT_ROOT / "configs" / "scenarios" / "foraging"
_MLP = "mlpppo_small_continuous2d_fick_adaptive_klinotaxis_hard350_ppo_w64"
_CONNECTOME = "connectomeppo_small_continuous2d_fick_adaptive_klinotaxis_hard350"
# Child stem -> (parent stem, brain-config changes beyond reversal).
CHILDREN: dict[str, tuple[str, dict[str, Any]]] = {
    f"{_MLP}_reversal": (_MLP, {}),
    f"{_MLP}_reversal_frozen": (_MLP, {"freeze_updates": True}),
    f"{_CONNECTOME}_emmons_reversal": (
        _CONNECTOME,
        {"connectome_source": "emmons_2024_hermaphrodite"},
    ),
    f"{_CONNECTOME}_frozen_emmons_reversal": (
        f"{_CONNECTOME}_frozen",
        {"connectome_source": "emmons_2024_hermaphrodite"},
    ),
}


def derive(child: str) -> tuple[Path, str]:
    """Build one config: its parent with reversal on and its listed brain changes."""
    parent, brain_changes = CHILDREN[child]
    data = yaml.safe_load((FORAGING / f"{parent}.yml").read_text())
    data["environment"]["continuous"]["allow_reversal"] = True
    data["brain"]["config"]["signed_speed"] = True
    data["brain"]["config"].update(brain_changes)
    lines = [
        "environment.continuous.allow_reversal: true",
        "brain.config.signed_speed: true",
        *(f"brain.config.{k}: {v}" for k, v in brain_changes.items()),
    ]
    header = (
        f"# C.0 validation arm: {child}.\n#\n# Delta from {parent}.yml, and nothing else changes:\n"
        + "".join(f"#   {line}\n" for line in lines)
        + "#\n# Generated by scripts/campaigns/generate_body_prerequisite_configs.py; re-checked\n"
        "# through the real config loader by test_body_prerequisites.py.\n#\n"
    )
    return FORAGING / f"{child}.yml", header + yaml.safe_dump(data, sort_keys=False)


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.parse_args(argv)
    written = 0
    for child in CHILDREN:
        path, text = derive(child)
        if not path.exists():
            path.write_text(text)
            written += 1
    print(f"wrote {written} configs; kept {len(CHILDREN) - written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
