#!/usr/bin/env python
"""Emit M.8's configs: the gap-only null and plastic gap junctions on the thermal cell at target 35.

Each config is a committed thermal target-35 parent with only the listed brain keys changed, and a
test re-reads every file through the real loader to check it. A config that already exists is left
alone, never overwritten.

Usage::

    uv run python scripts/campaigns/generate_plastic_gap_configs.py
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
THERMAL = PROJECT_ROOT / "configs" / "scenarios" / "thermal_foraging"
_T = "connectomeppo_small_continuous2d_thermal_klinotaxis"
_GAP_ONLY = {"wiring": "rewired_gap_junctions_only"}
_PLASTIC = {"plastic_gaps": True}
# Child stem -> (parent stem, brain-config changes).
CHILDREN: dict[str, tuple[str, dict[str, Any]]] = {
    f"{_T}_rewired_gap_only_null_t35": (f"{_T}_t35", _GAP_ONLY),
    f"{_T}_rewired_gap_only_null_frozen_t35": (f"{_T}_frozen_t35", _GAP_ONLY),
    f"{_T}_plastic_gaps_t35": (f"{_T}_t35", _PLASTIC),
    f"{_T}_rewired_gap_only_null_plastic_gaps_t35": (f"{_T}_t35", {**_GAP_ONLY, **_PLASTIC}),
}


def derive(child: str) -> tuple[Path, str]:
    """Build one config: its parent with its listed brain changes."""
    parent, changes = CHILDREN[child]
    data = yaml.safe_load((THERMAL / f"{parent}.yml").read_text())
    data["brain"]["config"].update(changes)
    header = (
        f"# M.8 arm: {child}.\n#\n# Delta from {parent}.yml, and nothing else changes:\n"
        + "".join(f"#   brain.config.{k}: {v}\n" for k, v in changes.items())
        + "#\n# Generated by scripts/campaigns/generate_plastic_gap_configs.py; re-checked through\n"
        "# the real config loader by test_plastic_gaps_panel.py.\n#\n"
    )
    return THERMAL / f"{child}.yml", header + yaml.safe_dump(data, sort_keys=False)


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.parse_args(argv)
    written = 0
    for child in CHILDREN:
        path, text = derive(child)
        if not path.exists():
            path.write_text(text)
            written += 1
    print(f"wrote {written} configs; kept {len(CHILDREN) - written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
