#!/usr/bin/env python
"""Emit C.3's control configs: MLP-PPO through the body in derivative sensing, learning and frozen.

The control is C.1e's MLP arm with ``chemotaxis_mode: derivative``, which has no spatial head-sweep,
so a weathervane that survives it is the body's own and one that collapses was the sweep's. The
frozen arm is its floor. Each config is re-checked through the real loader by a test; a config that
already exists is left alone.

Usage::

    uv run python scripts/campaigns/generate_body_validation_configs.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import generate_body_wiring_configs as wiring  # noqa: E402  # pyright: ignore[reportMissingImports]

FORAGING = wiring.FORAGING
CONTROL_STEM = f"{wiring.MLP_STEM}_derivative"


def stem(arm: str) -> str:
    """Return the control's stem for ``learn`` or ``frozen``."""
    return CONTROL_STEM if arm == "learn" else f"{CONTROL_STEM}_frozen"


def derive(arm: str) -> tuple[Path, str]:
    """Build one control arm from C.1e's MLP config with derivative sensing."""
    data: dict[str, Any] = yaml.safe_load((FORAGING / f"{wiring.MLP_STEM}.yml").read_text())
    data["environment"]["sensing"]["chemotaxis_mode"] = "derivative"
    lines = ["environment.sensing.chemotaxis_mode: derivative"]
    if arm == "frozen":
        data["brain"]["config"]["freeze_updates"] = True
        lines.append("brain.config.freeze_updates: true")
    child = stem(arm)
    header = (
        f"# C.3 control arm: {child}.\n#\n# Delta from {wiring.MLP_STEM}.yml, and nothing else "
        "changes:\n"
        + "".join(f"#   {line}\n" for line in lines)
        + "#\n# Generated by scripts/campaigns/generate_body_validation_configs.py; re-checked\n"
        "# through the real config loader by test_body_validation.py.\n#\n"
    )
    return FORAGING / f"{child}.yml", header + yaml.safe_dump(data, sort_keys=False)


def main() -> int:
    """CLI: write both control configs if missing."""
    written = 0
    for arm in ("learn", "frozen"):
        path, text = derive(arm)
        if not path.exists():
            path.write_text(text)
            written += 1
    print(f"wrote {written} configs; kept {2 - written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
