#!/usr/bin/env python
"""Emit A.2's sweep configs: each committed parent plus exactly one explicit pin.

There is no configuration-override mechanism in this repository -- no ``extends``, no ``--set`` --
and the campaign runner hands the same passthrough to every run, so it could not vary a pin across
arms even if one existed. Every grid point is therefore a committed file, and at seventy-odd points
that is a generator's job rather than an authoring one. The generated files are committed like any
other config; this script exists so the one-key claim is mechanical rather than manual, and a test
re-reads every file through the real loader to check it held.

The panel itself is defined once, in ``scripts/analysis/operating_point_surface.py``, and imported
here. A generator with its own copy of the grid is a generator that will disagree with the analysis
about what ran.

**A config that already exists is left alone**, never overwritten. Fifteen arms of this panel are
committed for earlier rungs -- the four block-V arms serving the PPO centre, and eleven e-prop arms
across the reading half's centre, ``wide`` and rate levels -- and they serve their levels unchanged,
which is the precedent A.1 set and what keeps their own tests' identity claims true.

Usage::

    uv run python scripts/campaigns/generate_operating_point_configs.py --dry-run
    uv run python scripts/campaigns/generate_operating_point_configs.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

_ANALYSIS = Path(__file__).resolve().parents[1] / "analysis"
if str(_ANALYSIS) not in sys.path:
    sys.path.insert(0, str(_ANALYSIS))

import operating_point_surface as ops  # noqa: E402  # pyright: ignore[reportMissingImports]

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = PROJECT_ROOT / "configs" / "scenarios" / "foraging"

_HALF_LABEL = {"ppo": "PPO", "reading": "reading-learner"}

# What each pin does, in one clause, so a file says why it exists without sending the reader to the
# roadmap. Keys are the pin names; the text lands in the generated header.
_PIN_NOTE = {
    "readout_width": "the motor readout's width, 8 pooled parameters against 78 per-neuron ones",
    "forward_pass_depth": "the settling depth, how many recurrence hops run between sensor "
    "injection and motor pooling",
    "initial_log_std": "the initial continuous action noise",
    "plasticity_rate": "the plasticity rule's step size",
    "trace_decay": "the eligibility trace's leak, which sets the credit-assignment horizon",
}


def _guard(pin: str, value: Any, config: dict[str, Any]) -> None:
    """Refuse a level the brain or the loader would refuse, at the point it is written.

    Each of these is a real rejection in the codebase rather than a defensive flourish, and two of
    them fire somewhere other than where a reader would look for them.
    """
    if pin == "forward_pass_depth" and int(value) < 1:
        # Refused in the topology constructor, not by the config model, so a bad file loads
        # cleanly and dies one step later.
        msg = f"forward_pass_depth must be >= 1, got {value}"
        raise ValueError(msg)
    if (
        pin == "initial_log_std"
        and float(value) != 0.0
        and config.get("continuous_std_mode") == "state_dependent"
    ):
        # Refused by a config validator: the state-dependent head computes its log-std from the
        # hidden state, so a non-zero value here would silently do nothing.
        msg = "initial_log_std has no effect under the state-dependent std head"
        raise ValueError(msg)


def header(half: str, arm: str, pin: str, value: Any, parent: str) -> str:
    """Write the house-convention header: what this arm is, and the single key that makes it so."""
    return (
        f"# Operating-point surface arm ({_HALF_LABEL[half]} half, {arm}) — "
        f"{pin} at {value!r} (Phase 8 A.2).\n"
        f"#\n"
        f"# Single-key delta from {parent}.yml:\n"
        f"#   {pin}: {value}\n"
        f"# and nothing else changes. The pin is {_PIN_NOTE[pin]}.\n"
        f"#\n"
        f"# One point of the one-factor-at-a-time pass around the committed operating point, which\n"
        f"# the parent carries unchanged as this half's centre arm.\n"
        f"#\n"
        f"# Generated by scripts/campaigns/generate_operating_point_configs.py. The body below is\n"
        f"# the parent's keys, re-emitted -- the parent's own header comments do not survive the\n"
        f"# round trip, so read that file for the cell's provenance. The single-key claim above is\n"
        f"# re-checked through the real config loader by test_operating_point_configs.py, so it is\n"
        f"# tested rather than asserted.\n"
        f"#\n"
    )


def derive(half: str, arm: str, suffix: str, pin: str, value: Any) -> tuple[Path, str]:
    """Build one config's path and text: the parent, plus that one key under ``brain.config``."""
    parent_stem = ops.CENTRE_STEMS[half][arm]
    parent = CONFIG_DIR / f"{parent_stem}.yml"
    data = yaml.safe_load(parent.read_text())
    brain_config = data["brain"]["config"]
    _guard(pin, value, brain_config)
    brain_config[pin] = value
    target = CONFIG_DIR / f"{ops.stem_for(half, arm, suffix)}.yml"
    return target, header(half, arm, pin, value, parent_stem) + yaml.safe_dump(data, sort_keys=False)


def plan() -> list[tuple[Path, str, bool]]:
    """Every file the panel needs, as ``(path, text, already_committed)`` in panel order."""
    out: list[tuple[Path, str, bool]] = []
    for half in ops.HALVES:
        for pin, suffix, value in ops._levels(half):  # noqa: SLF001
            for arm in ops.arms_at(half, suffix):
                target, text = derive(half, arm, suffix, pin, value)
                out.append((target, text, target.exists()))
    return out


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config of the panel, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="list what would be written without writing it",
    )
    args = ap.parse_args(argv)

    written, kept = 0, 0
    for target, text, exists in plan():
        if exists:
            kept += 1
            continue
        written += 1
        if args.dry_run:
            print(f"would write {target.relative_to(PROJECT_ROOT)}")
        else:
            target.write_text(text)
    verb = "would write" if args.dry_run else "wrote"
    print(f"{verb} {written} configs; kept {kept} already committed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
