#!/usr/bin/env python
"""Emit the null-strength control's configs: each full-null arm with the chemical-only wiring.

The panel -- which arms are new and which committed arm each derives from -- is defined once, in
``scripts/analysis/null_strength_control.py``, and imported here. Each new config is its parent with
``wiring: rewired_chemical_only`` and nothing else; a test re-reads every file through the real
loader to check that. A config that already exists is left alone, never overwritten.

Usage::

    uv run python scripts/campaigns/generate_null_strength_configs.py --dry-run
    uv run python scripts/campaigns/generate_null_strength_configs.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_ANALYSIS = Path(__file__).resolve().parents[1] / "analysis"
if str(_ANALYSIS) not in sys.path:
    sys.path.insert(0, str(_ANALYSIS))

import null_strength_control as nsc  # noqa: E402  # pyright: ignore[reportMissingImports]

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = PROJECT_ROOT / "configs" / "scenarios" / "foraging"
WIRING = "rewired_chemical_only"
_HALF_LABEL = {"ppo": "PPO", "reading": "reading learner"}


def derive(stem: str) -> tuple[Path, str]:
    """Build one config's path and text: its full-null parent with the chemical-only wiring."""
    half, parent = nsc.NEW_ARMS[stem]
    data = yaml.safe_load((CONFIG_DIR / f"{parent}.yml").read_text())
    data["brain"]["config"]["wiring"] = WIRING
    header = (
        f"# Null-strength control arm ({_HALF_LABEL[half]}) — the chemical-only rewired null "
        f"(Phase 8 A.6).\n"
        f"#\n"
        f"# Delta from {parent}.yml, and nothing else changes:\n"
        f"#   wiring: {WIRING}\n"
        f"#\n"
        f"# The chemical graph is rewired by the same degree-preserving swap as the parent's null;\n"
        f"# the gap junctions (pairs and counts) and the autapses are held at the wild type's.\n"
        f"#\n"
        f"# Generated by scripts/campaigns/generate_null_strength_configs.py. The body below is the\n"
        f"# parent's keys, re-emitted -- the parent's own header comments do not survive the round\n"
        f"# trip, so read that file for the cell's provenance. The delta above is re-checked through\n"
        f"# the real config loader by test_null_strength_control.py.\n"
        f"#\n"
    )
    return CONFIG_DIR / f"{stem}.yml", header + yaml.safe_dump(data, sort_keys=False)


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--dry-run", action="store_true", help="list what would be written")
    args = ap.parse_args(argv)
    written, kept = 0, 0
    for stem in nsc.NEW_ARMS:
        target, text = derive(stem)
        if target.exists():
            kept += 1
            continue
        written += 1
        if args.dry_run:
            print(f"would write {target.relative_to(PROJECT_ROOT)}")
        else:
            target.write_text(text)
    print(f"{'would write' if args.dry_run else 'wrote'} {written} configs; kept {kept}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
