#!/usr/bin/env python
"""Emit the measured-prior configs: each committed parent plus its level's prior keys.

Two panels share these parents and this stem rule: the pilot, which swept the multiplier, and the
wiring x weight-prior contrast, which adds a shuffled level. There is no configuration-override
mechanism in this repository, so every arm at every level is a committed file. Each panel is defined
once -- ``scripts/analysis/measured_prior_pilot.py`` and ``measured_prior_contrast.py`` -- and
imported here, so the generator cannot disagree with the analysis about what ran.

A level adds **at most two keys** under ``brain.config``: ``weight_prior``, and
``measured_weight_scale`` where it is not the default. The random level is the parents themselves,
unchanged. A config that already exists is left alone, never overwritten. A test re-reads every file
through the real loader and checks it differs from its parent in exactly those keys.

Usage::

    uv run python scripts/campaigns/generate_measured_prior_configs.py --dry-run
    uv run python scripts/campaigns/generate_measured_prior_configs.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

_ANALYSIS = Path(__file__).resolve().parents[1] / "analysis"
if str(_ANALYSIS) not in sys.path:
    sys.path.insert(0, str(_ANALYSIS))

import measured_prior_contrast as mc  # noqa: E402  # pyright: ignore[reportMissingImports]
import measured_prior_pilot as mp  # noqa: E402  # pyright: ignore[reportMissingImports]

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = PROJECT_ROOT / "configs" / "scenarios" / "foraging"

_HALF_LABEL = {"ppo": "PPO, per-neuron fan-in draw", "reading": "reading learner"}
# (panel label, milestone, the test that re-checks the delta) for the panel a level first belongs to.
_PILOT = ("Measured-prior pilot arm", "B.1b", "test_measured_prior_pilot.py")
_CONTRAST = ("Wiring x weight-prior arm", "B.1c", "test_measured_prior_contrast.py")


def header(  # noqa: PLR0913 - the arm's coordinates and the panel it belongs to
    half: str,
    arm: str,
    suffix: str,
    keys: dict[str, Any],
    parent: str,
    panel: tuple[str, str, str] = _PILOT,
) -> str:
    """Write the house-convention header: what this arm is, and the keys that make it so."""
    label, milestone, test = panel
    key_lines = "".join(f"#   {k}: {v}\n" for k, v in keys.items())
    return (
        f"# {label} ({_HALF_LABEL[half]}, {arm}) — level {suffix} (Phase 8 {milestone}).\n"
        f"#\n"
        f"# Delta from {parent}.yml, and nothing else changes:\n"
        f"{key_lines}"
        f"#\n"
        f"# The chemical weights the fitted whole-brain model covers take its values (or, under\n"
        f"# measured_signs, its signs on the draw's magnitudes; under measured_shuffled, the same\n"
        f"# values permuted among the covered edges); every other edge keeps the draw.\n"
        f"# measured_weight_scale multiplies the matched magnitude; 1.0 is the random draw's.\n"
        f"#\n"
        f"# Generated by scripts/campaigns/generate_measured_prior_configs.py. The body below is the\n"
        f"# parent's keys, re-emitted -- the parent's own header comments do not survive the round\n"
        f"# trip, so read that file for the cell's provenance. The delta above is re-checked through\n"
        f"# the real config loader by {test}.\n"
        f"#\n"
    )


def derive(
    half: str,
    arm: str,
    suffix: str,
    panel: tuple[str, str, str] = _PILOT,
) -> tuple[Path, str]:
    """Build one config's path and text: the parent, plus the level's keys under ``brain.config``."""
    parent_stem = mp.PARENTS[half][arm]
    data = yaml.safe_load((CONFIG_DIR / f"{parent_stem}.yml").read_text())
    keys = mp.level_keys(suffix)
    data["brain"]["config"].update(keys)
    target = CONFIG_DIR / f"{mp.stem_for(half, arm, suffix)}.yml"
    return target, header(half, arm, suffix, keys, parent_stem, panel) + yaml.safe_dump(
        data,
        sort_keys=False,
    )


def plan() -> list[tuple[Path, str, bool]]:
    """Every file both panels need beyond their parents, as ``(path, text, already_committed)``.

    A level is written once, under the first panel that uses it: the contrast reuses the pilot's
    measured level, so only its shuffled level is its own.
    """
    levels = [(s, _PILOT) for s in mp.ALL_LEVELS]
    levels += [(s, _CONTRAST) for s in mc.LEVELS if s not in mp.ALL_LEVELS]
    out: list[tuple[Path, str, bool]] = []
    for half in mp.HALVES:
        for suffix, panel in levels:
            if suffix == mp.RANDOM:
                continue
            for arm in mp.ARMS:
                target, text = derive(half, arm, suffix, panel)
                out.append((target, text, target.exists()))
    return out


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config of the pilot, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="list what would be written without writing it",
    )
    args = ap.parse_args(argv)

    written, kept = 0, 0
    for target, text, exists in plan():
        if exists:
            kept += 1
            continue
        written += 1
        if args.dry_run:
            print(f"would write {target.relative_to(PROJECT_ROOT)}")
        else:
            target.write_text(text)
    verb = "would write" if args.dry_run else "wrote"
    print(f"{verb} {written} configs; kept {kept} already committed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
