#!/usr/bin/env python
"""Emit block V's thermal configs at another food target.

Block V's thermal cell runs at ``target_foods_to_collect: 20``, where every learning arm saturates
above the analyses' 90% bar. A panel that needs a readable thermal point runs the same configs at a
higher target. Each config written here is its target-20 parent with that one key changed, and a
test re-reads every file through the real loader to check it. A config that already exists is left
alone, never overwritten.

Usage::

    uv run python scripts/campaigns/generate_thermal_target_configs.py --target 35 --dry-run
    uv run python scripts/campaigns/generate_thermal_target_configs.py --target 35
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = PROJECT_ROOT / "configs" / "scenarios" / "thermal_foraging"
_T = "connectomeppo_small_continuous2d_thermal_klinotaxis"
SOURCE_TARGET = 20
# The arms a thermal wiring panel can need: the wild type, the current null and the gap-held null,
# each learning and frozen.
PARENTS: tuple[str, ...] = (
    f"{_T}_t20",
    f"{_T}_frozen_t20",
    f"{_T}_rewired_null_t20",
    f"{_T}_rewired_null_frozen_t20",
    f"{_T}_rewired_gap_held_null_t20",
    f"{_T}_rewired_gap_held_null_frozen_t20",
)


def child_stem(parent: str, target: int) -> str:
    """Return the stem of ``parent`` at ``target``."""
    return parent.replace(f"_t{SOURCE_TARGET}", f"_t{target}")


def derive(parent: str, target: int) -> tuple[Path, str]:
    """Build one config's path and text: its target-20 parent with the target changed."""
    data = yaml.safe_load((CONFIG_DIR / f"{parent}.yml").read_text())
    foraging = data["environment"]["foraging"]
    if foraging["target_foods_to_collect"] != SOURCE_TARGET:
        msg = f"{parent}.yml has target {foraging['target_foods_to_collect']}, expected 20"
        raise ValueError(msg)
    foraging["target_foods_to_collect"] = target
    header = (
        f"# Block V thermal arm at target {target}.\n"
        f"#\n"
        f"# Delta from {parent}.yml, and nothing else changes:\n"
        f"#   environment.foraging.target_foods_to_collect: {target}\n"
        f"#\n"
        f"# At target 20 every learning arm plateaus above the 90% saturation bar, so a wiring\n"
        f"# contrast there is unreadable. The target is chosen by a gate-only pilot.\n"
        f"#\n"
        f"# Generated by scripts/campaigns/generate_thermal_target_configs.py. The body below is the\n"
        f"# parent's keys, re-emitted -- read that file for the cell's provenance. The delta above is\n"
        f"# re-checked through the real config loader by test_thermal_split.py.\n"
        f"#\n"
    )
    return CONFIG_DIR / f"{child_stem(parent, target)}.yml", header + yaml.safe_dump(
        data,
        sort_keys=False,
    )


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config at the target, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--target", type=int, required=True)
    ap.add_argument("--dry-run", action="store_true", help="list what would be written")
    args = ap.parse_args(argv)
    written, kept = 0, 0
    for parent in PARENTS:
        path, text = derive(parent, args.target)
        if path.exists():
            kept += 1
            continue
        written += 1
        if args.dry_run:
            print(f"would write {path.relative_to(PROJECT_ROOT)}")
        else:
            path.write_text(text)
    print(f"{'would write' if args.dry_run else 'wrote'} {written} configs; kept {kept}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
