#!/usr/bin/env python
"""Emit C.1d's configs: MLP-PPO through the kinematic body on hard350, learning and frozen.

Every config is C.0's committed MLP-PPO reversal pair with the body switched on: the kinematic body
model, the 25-number body-drive action space, and signed speed removed (the body's direction channel
reverses it). Beyond that:

* ``--stage pilot``: the steering calibration, one pair per candidate gain, with the gain set.
* ``--stage control --gain G``: the positive control, with no gain set, so the body's default
  applies. It refuses unless ``G`` is that default, so the control cannot run before the pilot's
  choice is frozen into the body.
* ``--stage fallback --steps N``: the control at a longer episode, for the competence fallback.

Each config is re-checked through the real loader by a test. A config that already exists is left
alone, never overwritten.

Usage::

    uv run python scripts/campaigns/generate_body_control_configs.py --stage pilot
    uv run python scripts/campaigns/generate_body_control_configs.py --stage control --gain 2
    uv run python scripts/campaigns/generate_body_control_configs.py --stage fallback --steps 500
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import quantumnematode.brain  # noqa: F401 - the package initialises brain before env
import yaml
from quantumnematode.env.body import BodyParams

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FORAGING = PROJECT_ROOT / "configs" / "scenarios" / "foraging"
_MLP = "mlpppo_small_continuous2d_fick_adaptive_klinotaxis_hard350_ppo_w64"
PARENTS = {"learn": f"{_MLP}_reversal", "frozen": f"{_MLP}_reversal_frozen"}
BODY = f"{_MLP}_body"
GAINS: tuple[float, ...] = (0.5, 1.0, 2.0, 4.0)
FALLBACK_STEPS: tuple[int, ...] = (500, 700, 1000)


def gain_label(gain: float) -> str:
    """Return a gain as a stem fragment: 0.5 -> ``gain0p5``, 2.0 -> ``gain2``."""
    return "gain" + f"{gain:g}".replace(".", "p")


def stem(arm: str, *, gain: float | None = None, steps: int | None = None) -> str:
    """Return the stem of one arm's config, ``learn`` or ``frozen``."""
    parts = [BODY]
    if gain is not None:
        parts.append(gain_label(gain))
    if steps is not None:
        parts.append(f"steps{steps}")
    if arm == "frozen":
        parts.append("frozen")
    return "_".join(parts)


def derive(arm: str, *, gain: float | None = None, steps: int | None = None) -> tuple[Path, str]:
    """Build one config from its C.0 parent with the body on and the listed changes."""
    parent = PARENTS[arm]
    data: dict[str, Any] = yaml.safe_load((FORAGING / f"{parent}.yml").read_text())
    continuous = data["environment"]["continuous"]
    continuous["body_model"] = "kinematic"
    data["brain"]["config"]["action_space"] = "body_drive"
    del data["brain"]["config"]["signed_speed"]
    lines = [
        "environment.continuous.body_model: kinematic",
        "brain.config.action_space: body_drive",
        "brain.config.signed_speed: removed",
    ]
    if gain is not None:
        continuous["body_steering_gain"] = gain
        lines.append(f"environment.continuous.body_steering_gain: {gain:g}")
    if steps is not None:
        data["max_steps"] = steps
        lines.append(f"max_steps: {steps}")
    child = stem(arm, gain=gain, steps=steps)
    header = (
        f"# C.1d arm: {child}.\n#\n# Delta from {parent}.yml, and nothing else changes:\n"
        + "".join(f"#   {line}\n" for line in lines)
        + "#\n# Generated by scripts/campaigns/generate_body_control_configs.py; re-checked\n"
        "# through the real config loader by test_body_control.py.\n#\n"
    )
    return FORAGING / f"{child}.yml", header + yaml.safe_dump(data, sort_keys=False)


def stage_configs(
    stage: str,
    *,
    gain: float | None = None,
    steps: int | None = None,
) -> list[tuple[Path, str]]:
    """Return every ``(path, text)`` one stage writes."""
    if stage == "pilot":
        return [derive(arm, gain=g) for g in GAINS for arm in PARENTS]
    if stage == "control":
        default = BodyParams().steering_gain
        if gain is None or gain != default:
            msg = (
                f"the control runs at the body's default steering gain ({default:g}); freeze the "
                f"pilot's choice ({gain}) into BodyParams first"
            )
            raise ValueError(msg)
        return [derive(arm) for arm in PARENTS]
    if stage == "fallback":
        if steps not in FALLBACK_STEPS:
            msg = f"the fallback lengths are {FALLBACK_STEPS}; got {steps}"
            raise ValueError(msg)
        return [derive(arm, steps=steps) for arm in PARENTS]
    msg = f"unknown stage {stage!r}"
    raise ValueError(msg)


def main(argv: list[str] | None = None) -> int:
    """CLI: write every missing config of one stage, and report what was already there."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--stage", choices=("pilot", "control", "fallback"), required=True)
    ap.add_argument("--gain", type=float, default=None)
    ap.add_argument("--steps", type=int, default=None)
    args = ap.parse_args(argv)
    configs = stage_configs(args.stage, gain=args.gain, steps=args.steps)
    written = 0
    for path, text in configs:
        if not path.exists():
            path.write_text(text)
            written += 1
    print(f"wrote {written} configs; kept {len(configs) - written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
