"""Constants."""

# Superposition mode
SUPERPOSITION_MODE_MAX_SUPERPOSITIONS = 16
SUPERPOSITION_MODE_MAX_COLUMNS = 4
SUPERPOSITION_MODE_RENDER_SLEEP_SECONDS = 1.0
SUPERPOSITION_MODE_TOP_N_ACTIONS = 2
SUPERPOSITION_MODE_TOP_N_RANDOMIZE = True
