max_steps: 300
maze_grid_size: 10
brain: classic
shots: 1000
body_length: 2
qubits: 2
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.1
    decay_rate: 0.001
    decay_type: inverse_time
gradient:
  method: clip
