max_steps: 200
maze_grid_size: 5
brain: dynamic
shots: 1000
body_length: 2
qubits: 8
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.01
    decay_rate: 0.001
    decay_type: inverse_time
gradient:
  method: clip
