max_steps: 300
maze_grid_size: 10
brain: dynamic
shots: 1000
body_length: 2
qubits: 2
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.01
    decay_rate: 0.001
gradient:
  method: clip
