max_steps: 300
maze_grid_size: 10
brain: modular
shots: 1000
body_length: 2
qubits: 2
learning_rate:
  method: dynamic
  parameters:
    initial_learning_rate: 0.1
    decay_rate: 0.001
    decay_type: inverse_time
gradient:
  method: clip
modules:
  chemotaxis: [0, 1]
superposition_mode:
  max_superpositions: 32
  max_columns: 8
  render_sleep_seconds: 0.5
  top_n_actions: 2
  top_n_randomize: true
